import dotenv from "dotenv";

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYwNTY2MDkwLCJleHAiOjE3NjA1NjY2OTB9.Gw34y-67Jqg3vV68aZkz8So0qtGCSXiX19zUTUAc8bI
@baseUrl = http://localhost:3000

### ================== RUTAS SIN AUTENTICACIÓN ==================

### Obtener todas las evaluaciones (SIN token)
GET {{baseUrl}}/api/assessments/public

### Obtener una evaluación por ID (SIN token)
GET {{baseUrl}}/api/assessments/public/1

### Crear una nueva evaluación (SIN token)
POST {{baseUrl}}/api/assessments/public
Content-Type: application/json

{
  "grade": 99,
  "feedback": "Excelente desempeño en el parcial",
  "date": "2025-10-15T10:00:00.000Z",
  "status": "ACTIVE",
  "submissionId": 1
}

### Actualizar una evaluación (SIN token)
PATCH {{baseUrl}}/api/assessments/public/452
Content-Type: application/json

{
  "grade": 80,
  "feedback": "Excelente mejora en el parcial",
  "date": "2025-10-20T10:00:00.000Z",
  "status": "ACTIVE",
  "submissionId": 1
}

### Eliminar una evaluación físicamente (SIN token)
DELETE {{baseUrl}}/api/assessments/public/452

### Eliminar una evaluación lógicamente (SIN token)
DELETE {{baseUrl}}/api/assessments/public/1/logic

### ================== RUTAS CON AUTENTICACIÓN ==================

### Obtener todas las evaluaciones (CON token)
GET {{baseUrl}}/api/assessments
Authorization: Bearer {{token}}

### Obtener una evaluación por ID (CON token)
GET {{baseUrl}}/api/assessments/2
Authorization: Bearer {{token}}

### Crear una nueva evaluación (CON token)
POST {{baseUrl}}/api/assessments
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "grade": 90,
  "feedback": "Buen desempeño en el parcial",
  "date": "2025-10-15T10:00:00.000Z",
  "status": "ACTIVE",
  "submissionId": 1
}

### Actualizar una evaluación (CON token)
PATCH {{baseUrl}}/api/assessments/453
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "grade": 95,
  "feedback": "Excelente mejora en el parcial",
  "date": "2025-10-20T10:00:00.000Z",
  "status": "ACTIVE",
  "submissionId": 1
}

### Eliminar una evaluación físicamente (CON token)
DELETE {{baseUrl}}/api/assessments/453
Authorization: Bearer {{token}}

### Eliminar una evaluación lógicamente (CON token)
DELETE {{baseUrl}}/api/assessments/2/logic
Authorization: Bearer {{token}}
